### ISSUE TITLE
Ext shortcuts: main menu barely usable

### ISSUE THREAD

**Issue by gene-pavlovsky** [wise0704/FlashDevelop#2]
Press Alt-F. File menu opens, you can open menu items using their letters, but:
  - Arrow keys don't work (expect to be able to move around the menu with arrow keys)
  - Esc keys don't work (first Esc should close the current menu but still focus on the menu, can use left/right to navigate, second Esc should unfocus the menu)

**Comment by wise0704** [comment]
Thanks for the reports! Unfortunately, I'm busy lately, so the fixes will be quite delayed...

It seems that (on my local branch) this issue happens when the scintilla control has focus (it eats the arrow keys when focused).
When other controls (e.g. Project tree) has focus, the keys work for the menu navigation & focus.

**Comment by gene-pavlovsky** [comment]
My pleasure. I've been waiting for this feature for a long time, can wait a long time more :)

**Comment by wise0704** [comment]
Fixed with c7bb7a8d5eeb205a6090689586ab9a0b2a02bc8b

Although the fix was only 2 lines, it took me ages to figure out how to fix this haha. It's .NET's fault for weird focus management with menu strips.
