### ISSUE TITLE
Ext shortcuts: shortcut dialog: adding duplicate issue

### ISSUE THREAD

**Issue by gene-pavlovsky** [wise0704/FlashDevelop#5]
1) Assign a shortcut to an action that has none, e.g. Ctrl+5, Ctrl+9 to Debug.DisableAllBreakpoints
2) Assign same shortcut to Debug.EnableAllBreakpoints. 
3) A dialog is shown, with abort/retry/ignore buttons, "retry" is not retry but "add anyway and show all action with same shortcut" - should be renamed, and I think "cancel" would be better than "abort".
4) Click "abort" in the dialog.
5) Bug: the shortcut keys entry box is not cleared, still displays Ctrl+5, Ctrl+9.
6) Click "Add" again. The entry box is cleared, but...
7) Enter another shortcut, e.g. Ctrl+5, Ctrl+8 for the same action, then "Add".
8) Bug: Debug.EnableAllBreakpoints now shows "None; Ctrl+5, Ctrl+8" shortcuts (None shouldn't be there)

**Comment by wise0704** [comment]
I would've never been able to find this bug... at least not soon enough.

One note: Abort/Retry/Ignore can't really be customised (using `MessageBox`) because Microsoft is a bully. I could add and use a custom form instead, with buttons with more descriptive labels, but that's kind of an overkill adding a form for just this use. Well this is separate issue anyway.

**Comment by gene-pavlovsky** [comment]
Buttons labels is just a cosmetic issue, I agree. No loss of functionality if you just leave it as it is.

**Comment by wise0704** [comment]
Fixed with 5c6215d9222268a503e588bc008cd3b00ec2cbe4
